-- Deprecated compatibility stub.
--
-- Older PropHunt builds tried to create a custom Gaussian blur PostEffect here,
-- but some BeamNG versions do not ship the referenced gaussianBlurP.hlsl shader.
-- The seeker hide-phase cover now uses prophuntBlurAPI -> prophuntVignetteAPI,
-- which avoids missing shader errors while keeping the screen obscured.
